#!/usr/bin/env -S node --no-warnings
import { writeFileSync, readFileSync, existsSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { Store } from "./store.ts";
import { parseReport } from "./seed.ts";
import { proposeEdges } from "./consolidate.ts";
import { milestoneDetail, milestoneSummary, resumeDigest, trace, traceEntity } from "./projections.ts";
import { renderResume } from "./render.ts";
import { stubResolver } from "./resolver.ts";
import { resolveDbPath, SteleNotInitializedError } from "./paths.ts";
import { startServerForeground } from "./serve.ts";
import { installHooks, uninstallHooks, hooksStatus } from "./hooks.ts";
import { installDaemon, uninstallDaemon, daemonStatus } from "./daemon.ts";
import {
  allProjects,
  register as registerProject,
  unregister as unregisterProject,
} from "./registry.ts";
import { createHash } from "node:crypto";
import {
  applyCaptureTags,
  confirmProposal,
  ensureTag,
  getTagPolicy,
  getTagRequireReason,
  rejectProposal,
} from "./tags.ts";
import type {
  CapturePayload,
  EntityRef,
  Milestone,
  TaggingTargetKind,
} from "./types.ts";

function readStdin(): string {
  try { return readFileSync(0, "utf8"); } catch { return ""; }
}

// -----------------------------------------------------------------------------
// stele init — bootstrap a project: .stele/ + .stele/README.md + .gitignore
// entry + .mcp.json with the stele server registered.
// -----------------------------------------------------------------------------

const STELE_README = `# .stele/ — decision store for this project

This directory was created by \`stele init\`. It holds **decisions.db**, a
SQLite store of decision provenance for this project: every decision made
about the codebase — what was chosen, what was deferred, what's still
open — lives here as a node in a graph.

## Daily use

Open Claude Code in this project. When a decision crystallizes in the
conversation, type \`/decision\` — the agent drafts the full record and
asks you to confirm.

To see what's waiting on you, ask: *"what's waiting on me?"* The agent
calls \`decision_resume\` and surfaces every open + un-resolved deferred
node, with the most-likely-due ones first.

## Cross-project view

If you organize multiple projects under one parent directory, run
\`stele init\` in the parent too. Decisions captured from any
subdirectory roll up into the parent's \`.stele/\`, giving you a global
view across all the projects under it.

## Backup

\`decisions.db\` is a regular SQLite file. Copy it while no MCP server
is connected. For a hot backup:

    sqlite3 decisions.db ".backup target.db"

## Sharing with a team

By default \`stele init\` adds \`.stele/\` to your project's \`.gitignore\`.
To share decisions with collaborators via git, remove that entry — the
DB file is small and version-friendly for small teams.

---

*Auto-generated by \`stele init\`. Safe to edit or delete. The tool
itself was installed via \`npm install -g stele-mcp\`.*
`;

async function initCommand(args: string[]): Promise<void> {
  let skipDaemon = false;
  let skipHooks = false;
  let port = 3939;
  for (let i = 0; i < args.length; i++) {
    const a = args[i];
    if (a === "--skip-daemon") skipDaemon = true;
    else if (a === "--skip-hooks") skipHooks = true;
    else if (a === "--port") {
      const n = Number(args[++i]);
      if (!Number.isInteger(n) || n < 1 || n > 65535) {
        console.error(`invalid --port value: ${args[i]}`);
        process.exit(1);
      }
      port = n;
    } else {
      console.error(`unknown init flag: ${a}`);
      process.exit(1);
    }
  }

  const cwd = process.cwd();
  const steleDir = join(cwd, ".stele");

  if (existsSync(steleDir)) {
    console.error(`stele already initialized at ${steleDir}`);
    console.error(`(rm -rf .stele to reset — you'll lose all decisions)`);
    process.exit(1);
  }

  mkdirSync(steleDir, { recursive: true });
  writeFileSync(join(steleDir, "README.md"), STELE_README);

  const gitignorePath = join(cwd, ".gitignore");
  let gitignoreNote = "";
  if (existsSync(gitignorePath)) {
    const current = readFileSync(gitignorePath, "utf8");
    if (!/^\.stele\/?$/m.test(current)) {
      const sep = current.endsWith("\n") || current.length === 0 ? "" : "\n";
      writeFileSync(gitignorePath, current + sep + ".stele/\n");
      gitignoreNote = "added .stele/ to .gitignore";
    } else {
      gitignoreNote = ".gitignore already mentions .stele/";
    }
  } else {
    writeFileSync(gitignorePath, ".stele/\n");
    gitignoreNote = "wrote .gitignore with .stele/";
  }

  const mcpPath = join(cwd, ".mcp.json");
  let mcpConfig: { mcpServers?: Record<string, unknown> } = { mcpServers: {} };
  let mcpNote = "wrote .mcp.json with stele entry";
  if (existsSync(mcpPath)) {
    let parsed: unknown;
    try {
      parsed = JSON.parse(readFileSync(mcpPath, "utf8"));
    } catch {
      console.error(`existing .mcp.json is not valid JSON — refusing to overwrite`);
      process.exit(1);
    }
    if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
      console.error(`existing .mcp.json is not an object — refusing to overwrite`);
      process.exit(1);
    }
    mcpConfig = parsed as typeof mcpConfig;
    if (!mcpConfig.mcpServers || typeof mcpConfig.mcpServers !== "object") {
      mcpConfig.mcpServers = {};
    }
    mcpNote = mcpConfig.mcpServers!.stele
      ? "updated stele entry in existing .mcp.json"
      : "merged stele entry into existing .mcp.json";
  }
  mcpConfig.mcpServers!.stele = { command: "stele-mcp" };
  writeFileSync(mcpPath, JSON.stringify(mcpConfig, null, 2) + "\n");

  console.log(`stele initialized at ${steleDir}`);
  console.log(``);
  console.log(`  wrote .stele/README.md`);
  console.log(`  ${mcpNote}`);
  console.log(`  ${gitignoreNote}`);

  // Register this project in the global registry so the multi-tenant daemon
  // can route /<slug>/ to it.
  let projectSlug: string;
  try {
    const reg = registerProject(cwd);
    projectSlug = reg.slug;
    console.log(`  ${reg.isNew ? "registered" : "already registered"} as slug "${reg.slug}"`);
  } catch (e) {
    projectSlug = "<this-project>";
    console.error(`  ⚠ registry write failed (continuing): ${(e as Error).message}`);
  }

  // Default-install hooks (Stop hook + stele-capture skill) — opt-out with --skip-hooks
  if (!skipHooks) {
    try {
      const r = installHooks(cwd);
      console.log(`  ${r.hook}`);
      console.log(`  ${r.skill}`);
      console.log(`  ${r.command}`);
      console.log(`  ${r.settings}`);
    } catch (e) {
      console.error(`  ⚠ hooks install failed (continuing): ${(e as Error).message}`);
    }
  }

  // Default-install daemon (launchd / systemd) — opt-out with --skip-daemon.
  // Install is idempotent: if already installed, nothing happens but legacy
  // per-project plists/units (from pre-0.0.3) get swept and their projects
  // get registered into the global registry.
  if (!skipDaemon) {
    if (process.platform !== "darwin" && process.platform !== "linux") {
      console.log(`  ⓘ daemon not installed (unsupported platform: ${process.platform})`);
    } else {
      try {
        const r = await installDaemon({ port });
        console.log(`  installed ${r.platform} daemon — http://127.0.0.1:${r.port} (loaded: ${r.loaded ? "yes" : "no"})`);
        for (const n of r.notes) console.log(`    · ${n}`);
      } catch (e) {
        console.error(`  ⚠ daemon install failed (continuing): ${(e as Error).message}`);
        console.error(`    you can retry with: stele daemon install --port <N>`);
      }
    }
  }

  console.log(``);
  console.log(`Next:`);
  console.log(`  1. Restart Claude Code in this directory (it picks up .mcp.json).`);
  if (skipDaemon) {
    console.log(`  2. Run \`stele serve --multi\` to launch the browser UI.`);
  } else {
    console.log(`  2. Open http://127.0.0.1:${port}/${projectSlug}/ — daemon serves it always-on.`);
  }
  console.log(`  3. Ask "what's waiting on me?" to see open loops.`);
}

// -----------------------------------------------------------------------------

function hooksCommand(args: string[]): void {
  const sub = args[0];
  const cwd = process.cwd();
  if (sub === "install") {
    try {
      const r = installHooks(cwd);
      console.log(`hooks installed in ${cwd}:`);
      console.log(`  ${r.hook}`);
      console.log(`  ${r.skill}`);
      console.log(`  ${r.command}`);
      console.log(`  ${r.settings}`);
    } catch (e) {
      console.error(`hooks install failed: ${(e as Error).message}`);
      process.exit(1);
    }
  } else if (sub === "uninstall") {
    try {
      const r = uninstallHooks(cwd);
      console.log(`hooks uninstalled from ${cwd}:`);
      console.log(`  ${r.hook}`);
      console.log(`  ${r.skill}`);
      console.log(`  ${r.command}`);
      console.log(`  ${r.settings}`);
    } catch (e) {
      console.error(`hooks uninstall failed: ${(e as Error).message}`);
      process.exit(1);
    }
  } else if (sub === "status" || sub === undefined) {
    const s = hooksStatus(cwd);
    const mark = (b: boolean) => (b ? "✓" : "✗");
    console.log(`stele hooks status (${cwd}):`);
    console.log(`  ${mark(s.hook)}  .claude/hooks/stele-stop.sh`);
    console.log(`  ${mark(s.skill)}  .claude/skills/stele-capture/SKILL.md`);
    console.log(`  ${mark(s.command)}  .claude/commands/decision.md`);
    console.log(`  ${mark(s.settingsHasEntry)}  Stop hook in .claude/settings.json`);
  } else {
    console.error(`unknown hooks subcommand: ${sub} — try install / uninstall / status`);
    process.exit(1);
  }
}

async function daemonCommand(args: string[]): Promise<void> {
  const sub = args[0];

  // Parse flags from args[1..]
  let port = 3939;
  let printUnit = false;
  for (let i = 1; i < args.length; i++) {
    const a = args[i];
    if (a === "--port") {
      const n = Number(args[++i]);
      if (!Number.isInteger(n) || n < 1 || n > 65535) {
        console.error(`invalid --port value: ${args[i]}`);
        process.exit(1);
      }
      port = n;
    } else if (a === "--print-unit") {
      printUnit = true;
    } else {
      console.error(`unknown daemon flag: ${a}`);
      process.exit(1);
    }
  }

  if (sub === "install") {
    try {
      const r = await installDaemon({ port, printUnit });
      if (printUnit) return; // unit printed to stdout already
      console.log(`stele daemon installed (${r.platform}, multi-tenant):`);
      console.log(`  unit:       ${r.unitPath}`);
      console.log(`  invocation: ${r.invocation}`);
      console.log(`  port:       ${r.port}`);
      console.log(`  loaded:     ${r.loaded ? "yes" : "no"}`);
      for (const n of r.notes) console.log(`  · ${n}`);
      if (r.legacy.registered.length > 0) {
        console.log(`  · imported projects from legacy daemons:`);
        for (const p of r.legacy.registered) console.log(`      ${p}`);
      }
      if (r.loaded) console.log(`\n  → http://127.0.0.1:${r.port}/`);
    } catch (e) {
      console.error(`daemon install failed: ${(e as Error).message}`);
      process.exit(1);
    }
  } else if (sub === "uninstall") {
    const r = uninstallDaemon();
    console.log(`stele daemon uninstalled:`);
    for (const n of r.notes) console.log(`  · ${n}`);
  } else if (sub === "status" || sub === undefined) {
    const s = daemonStatus();
    const n = allProjects().length;
    console.log(`stele daemon status:`);
    console.log(`  platform:           ${s.platform}`);
    console.log(`  unit file:          ${s.unitPresent ? "✓" : "✗"} ${s.unitPath}`);
    console.log(`  loaded:             ${s.loaded ? "✓" : "✗"} (${s.loadedNote})`);
    console.log(`  registered projects: ${n}`);
  } else {
    console.error(`unknown daemon subcommand: ${sub} — try install / uninstall / status`);
    process.exit(1);
  }
}

function projectsCommand(args: string[]): void {
  const sub = args[0];
  if (sub === undefined || sub === "list") {
    const projects = allProjects();
    if (projects.length === 0) {
      console.log(`no projects registered. Run \`stele init\` in a project root.`);
      return;
    }
    console.log(`${projects.length} registered project(s):`);
    const w = Math.max(...projects.map((p) => p.slug.length));
    for (const p of projects) {
      console.log(`  ${p.slug.padEnd(w)}  ${p.path}`);
    }
  } else if (sub === "remove") {
    const target = args[1];
    if (!target) {
      console.error(`stele projects remove <slug-or-path>`);
      process.exit(1);
    }
    const removed = unregisterProject(target);
    if (removed) console.log(`removed ${target} from registry`);
    else {
      console.error(`no project matched "${target}"`);
      process.exit(1);
    }
  } else {
    console.error(`unknown projects subcommand: ${sub} — try list / remove`);
    process.exit(1);
  }
}

async function serveCommand(args: string[]): Promise<void> {
  let port = 3939;
  let host = "127.0.0.1";
  let open = false;
  let multi = false;
  for (let i = 0; i < args.length; i++) {
    const a = args[i];
    if (a === "--port") {
      const n = Number(args[++i]);
      if (!Number.isInteger(n) || n < 1 || n > 65535) {
        console.error(`invalid --port value: ${args[i]}`);
        process.exit(1);
      }
      port = n;
    } else if (a === "--host") {
      host = args[++i];
      if (!host) {
        console.error(`--host requires a value`);
        process.exit(1);
      }
    } else if (a === "--open") {
      open = true;
    } else if (a === "--multi") {
      multi = true;
    } else {
      console.error(`unknown serve flag: ${a}`);
      process.exit(1);
    }
  }
  if (multi) {
    await startServerForeground({ multi: true, port, host, open });
    return;
  }
  // Single-project mode: resolve a store from cwd
  let store: Store;
  try {
    store = new Store(resolveDbPath());
  } catch (e) {
    if (e instanceof SteleNotInitializedError) {
      console.error(e.message);
      process.exit(1);
    }
    throw e;
  }
  await startServerForeground({ store, port, host, open });
}

// -----------------------------------------------------------------------------
// 0.0.6 — stele milestones {list, open, close, show}
// -----------------------------------------------------------------------------

function milestonesCommand(store: Store, args: string[]): void {
  const sub = args[0];

  if (sub === undefined || sub === "list") {
    // parse flags
    let json = false;
    let status: "active" | "shipped" | "abandoned" | undefined;
    for (let i = 1; i < args.length; i++) {
      const a = args[i];
      if (a === "--json") json = true;
      else if (a === "--status") {
        const v = args[++i];
        if (v !== "active" && v !== "shipped" && v !== "abandoned") {
          console.error(`invalid --status: ${v}`);
          process.exit(1);
        }
        status = v;
      } else {
        console.error(`unknown flag: ${a}`);
        process.exit(1);
      }
    }
    const summary = milestoneSummary(store);
    const filtered = status ? summary.filter((m) => m.milestone.status === status) : summary;
    if (json) {
      process.stdout.write(JSON.stringify(filtered, null, 2) + "\n");
      return;
    }
    if (filtered.length === 0) {
      console.log("no milestones");
      return;
    }
    for (const m of filtered) {
      const lo = m.openLoops > 0 ? ` · ${m.openLoops} open loop${m.openLoops === 1 ? "" : "s"}` : "";
      console.log(
        `  ${m.milestone.id}  [${m.milestone.status.padEnd(9)}]  ${m.milestone.title}  (${m.sessionCount} session${m.sessionCount === 1 ? "" : "s"}${lo})`,
      );
    }
    return;
  }

  if (sub === "open") {
    const title = args[1];
    if (!title) {
      console.error(`stele milestones open "title" [--intent "..."]`);
      process.exit(1);
    }
    let intent: string | undefined;
    for (let i = 2; i < args.length; i++) {
      const a = args[i];
      if (a === "--intent") intent = args[++i];
      else {
        console.error(`unknown flag: ${a}`);
        process.exit(1);
      }
    }
    const id = store.nextMilestoneId();
    const m: Milestone = {
      id, title, intent, status: "active",
      startedAt: new Date().toISOString(),
    };
    store.putMilestone(m);
    console.log(`opened ${id} "${title}"`);
    return;
  }

  if (sub === "close") {
    const id = args[1];
    if (!id) {
      console.error(`stele milestones close <id> [--shipped|--abandoned]`);
      process.exit(1);
    }
    let verdict: "shipped" | "abandoned" = "shipped";
    for (let i = 2; i < args.length; i++) {
      if (args[i] === "--shipped") verdict = "shipped";
      else if (args[i] === "--abandoned") verdict = "abandoned";
      else {
        console.error(`unknown flag: ${args[i]}`);
        process.exit(1);
      }
    }
    const existing = store.getMilestone(id);
    if (!existing) {
      console.error(`no such milestone: ${id}`);
      process.exit(1);
    }
    store.putMilestone({ ...existing, status: verdict, completedAt: new Date().toISOString() });
    console.log(`${id} → ${verdict}`);
    return;
  }

  if (sub === "show") {
    const id = args[1];
    if (!id) {
      console.error(`stele milestones show <id>`);
      process.exit(1);
    }
    const detail = milestoneDetail(store, id);
    if (!detail) {
      console.error(`no such milestone: ${id}`);
      process.exit(1);
    }
    console.log(`${detail.milestone.id}  ${detail.milestone.title}  [${detail.milestone.status}]`);
    if (detail.milestone.intent) console.log(`  intent: ${detail.milestone.intent}`);
    console.log(`  started: ${detail.milestone.startedAt}`);
    if (detail.milestone.completedAt) console.log(`  completed: ${detail.milestone.completedAt}`);
    console.log();
    for (const { session, decisions } of detail.sessions) {
      console.log(`  ${session.id}  (${session.source}${session.sourceSessionId ? `, ${session.sourceSessionId.slice(0, 8)}` : ""})  ${decisions.length} decision${decisions.length === 1 ? "" : "s"}`);
      for (const d of decisions) {
        console.log(`    ${d.id.padEnd(7)} ${d.status.kind.padEnd(11)} ${d.title}`);
      }
    }
    return;
  }

  console.error(`unknown milestones subcommand: ${sub} — try list / open / close / show`);
  process.exit(1);
}

// -----------------------------------------------------------------------------
// 0.0.7 — stele tags <list|propose|apply|confirm|reject|recolor|rename|archive|restore|proposals>
// -----------------------------------------------------------------------------

function parseTarget(spec: string | undefined): { kind: TaggingTargetKind; id: string } {
  if (!spec) {
    console.error(`expected target in form <kind>:<id> — e.g. decision:D-42 or milestone:M-03`);
    process.exit(1);
  }
  const idx = spec.indexOf(":");
  if (idx <= 0) {
    console.error(`bad target "${spec}" — expected <kind>:<id>`);
    process.exit(1);
  }
  const kind = spec.slice(0, idx);
  const id = spec.slice(idx + 1);
  if (kind !== "decision" && kind !== "milestone") {
    console.error(`target kind must be 'decision' or 'milestone', got "${kind}"`);
    process.exit(1);
  }
  return { kind, id };
}

function tagsCommand(store: Store, args: string[]): void {
  const sub = args[0] ?? "list";

  if (sub === "list") {
    let status: "active" | "archived" | "all" = "active";
    let json = false;
    for (let i = 1; i < args.length; i++) {
      if (args[i] === "--all") status = "all";
      else if (args[i] === "--archived") status = "archived";
      else if (args[i] === "--active") status = "active";
      else if (args[i] === "--json") json = true;
      else {
        console.error(`unknown flag: ${args[i]}`);
        process.exit(1);
      }
    }
    const list = status === "all" ? store.allTags() : store.allTags(status);
    if (json) {
      const enriched = list.map((t) => ({ ...t, targetCount: store.targetsForTag(t.id).length }));
      process.stdout.write(JSON.stringify(enriched, null, 2) + "\n");
      return;
    }
    if (list.length === 0) {
      console.log(`no ${status === "all" ? "" : status + " "}tags`);
      return;
    }
    for (const t of list) {
      const targets = store.targetsForTag(t.id);
      console.log(
        `  ${t.id.padEnd(14)} ${t.color}  ${t.status.padEnd(8)} ${t.origin.padEnd(5)}  ${t.name}  (${targets.length} target${targets.length === 1 ? "" : "s"})`,
      );
    }
    return;
  }

  if (sub === "proposals") {
    let outcome: "pending" | "blocked" | "auto_adopted" | undefined = "pending";
    for (let i = 1; i < args.length; i++) {
      if (args[i] === "--all") outcome = undefined;
      else if (args[i] === "--pending") outcome = "pending";
      else if (args[i] === "--blocked") outcome = "blocked";
      else if (args[i] === "--adopted") outcome = "auto_adopted";
      else {
        console.error(`unknown flag: ${args[i]}`);
        process.exit(1);
      }
    }
    const list = store.allTagProposals(outcome);
    if (list.length === 0) {
      console.log(`no ${outcome ?? ""} proposals`);
      return;
    }
    for (const p of list) {
      console.log(`  ${p.id.padEnd(12)} [${p.outcome.padEnd(12)}] ${p.name}  → ${p.targets.length} target(s)`);
      if (p.reason) console.log(`        reason: ${p.reason}`);
    }
    return;
  }

  if (sub === "propose") {
    const name = args[1];
    if (!name) {
      console.error(`stele tags propose <name> [--reason "..."] [--color #RRGGBB] [--target kind:id ...]`);
      process.exit(1);
    }
    let reason: string | undefined;
    let suggestedColor: string | undefined;
    const targets: { kind: TaggingTargetKind; id: string }[] = [];
    for (let i = 2; i < args.length; i++) {
      const a = args[i];
      if (a === "--reason") reason = args[++i];
      else if (a === "--color") suggestedColor = args[++i];
      else if (a === "--target") targets.push(parseTarget(args[++i]));
      else {
        console.error(`unknown flag: ${a}`);
        process.exit(1);
      }
    }
    if (targets.length === 0) {
      console.error(`at least one --target is required`);
      process.exit(1);
    }
    try {
      const r = ensureTag(store, name, { reason, suggestedColor, targets });
      if (r.kind === "active") console.log(`applied existing ${r.tag.id} (${r.tag.name})`);
      else if (r.kind === "pending") console.log(`proposed ${r.proposal.id} (${r.proposal.name}) — confirm with: stele tags confirm ${r.proposal.id}`);
      else console.log(`blocked by tag_policy=locked — logged ${r.proposal.id}`);
    } catch (e) {
      console.error(`error: ${(e as Error).message}`);
      process.exit(1);
    }
    return;
  }

  if (sub === "apply") {
    const tagId = args[1];
    const targetSpec = args[2];
    if (!tagId || !targetSpec) {
      console.error(`stele tags apply <tagId> <kind:id>`);
      process.exit(1);
    }
    const tag = store.getTag(tagId);
    if (!tag) {
      console.error(`no such tag: ${tagId}`);
      process.exit(1);
    }
    if (tag.status !== "active") {
      console.error(`tag ${tagId} is archived; restore it first`);
      process.exit(1);
    }
    const target = parseTarget(targetSpec);
    store.upsertTagging({ tagId, targetKind: target.kind, targetId: target.id });
    console.log(`${tag.name} → ${target.kind}:${target.id}`);
    return;
  }

  if (sub === "confirm") {
    const proposalId = args[1];
    if (!proposalId) {
      console.error(`stele tags confirm <proposalId> [--rename name] [--color #RRGGBB]`);
      process.exit(1);
    }
    let rename: string | undefined;
    let color: string | undefined;
    for (let i = 2; i < args.length; i++) {
      if (args[i] === "--rename") rename = args[++i];
      else if (args[i] === "--color") color = args[++i];
      else {
        console.error(`unknown flag: ${args[i]}`);
        process.exit(1);
      }
    }
    try {
      const r = confirmProposal(store, proposalId, { rename, color });
      console.log(`confirmed ${r.tag.id} (${r.tag.name}); ${r.taggingsAdded} new tagging(s) applied`);
    } catch (e) {
      console.error(`error: ${(e as Error).message}`);
      process.exit(1);
    }
    return;
  }

  if (sub === "reject") {
    const proposalId = args[1];
    if (!proposalId) {
      console.error(`stele tags reject <proposalId>`);
      process.exit(1);
    }
    const ok = rejectProposal(store, proposalId);
    if (!ok) {
      console.error(`no such proposal: ${proposalId}`);
      process.exit(1);
    }
    console.log(`rejected ${proposalId}`);
    return;
  }

  if (sub === "recolor") {
    const tagId = args[1];
    const color = args[2];
    if (!tagId || !color || !/^#[0-9a-fA-F]{6}$/.test(color)) {
      console.error(`stele tags recolor <tagId> <#RRGGBB>`);
      process.exit(1);
    }
    if (!store.getTag(tagId)) {
      console.error(`no such tag: ${tagId}`);
      process.exit(1);
    }
    store.recolorTag(tagId, color);
    console.log(`${tagId} → ${color}`);
    return;
  }

  if (sub === "rename") {
    const tagId = args[1];
    const name = args[2];
    if (!tagId || !name) {
      console.error(`stele tags rename <tagId> <newname>`);
      process.exit(1);
    }
    const existing = store.getTag(tagId);
    if (!existing) {
      console.error(`no such tag: ${tagId}`);
      process.exit(1);
    }
    const collision = store.findTagByName(name);
    if (collision && collision.id !== tagId) {
      console.error(`name "${name}" already taken by ${collision.id}`);
      process.exit(1);
    }
    store.renameTag(tagId, name);
    console.log(`${tagId} renamed → ${name}`);
    return;
  }

  if (sub === "archive") {
    const tagId = args[1];
    if (!tagId || !store.getTag(tagId)) {
      console.error(`stele tags archive <tagId>`);
      process.exit(1);
    }
    store.archiveTag(tagId);
    console.log(`${tagId} archived`);
    return;
  }

  if (sub === "restore") {
    const tagId = args[1];
    if (!tagId || !store.getTag(tagId)) {
      console.error(`stele tags restore <tagId>`);
      process.exit(1);
    }
    store.restoreTag(tagId);
    console.log(`${tagId} restored`);
    return;
  }

  console.error(`unknown tags subcommand: ${sub} — try list / proposals / propose / apply / confirm / reject / recolor / rename / archive / restore`);
  process.exit(1);
}

function configCommand(store: Store, args: string[]): void {
  const sub = args[0];
  if (sub === undefined || sub === "list") {
    const all = store.allConfig();
    const keys = Object.keys(all).sort();
    // Surface defaults inline so the user sees what's actually in effect.
    console.log(`  tag_policy         = ${all.tag_policy ?? getTagPolicy(store) + " (default)"}`);
    console.log(`  tag_require_reason = ${all.tag_require_reason ?? (getTagRequireReason(store) ? "true" : "false") + " (default)"}`);
    for (const k of keys) {
      if (k === "tag_policy" || k === "tag_require_reason") continue;
      console.log(`  ${k.padEnd(18)} = ${all[k]}`);
    }
    return;
  }
  if (sub === "get") {
    const key = args[1];
    if (!key) {
      console.error(`stele config get <key>`);
      process.exit(1);
    }
    const v = store.getConfig(key);
    if (v === null) {
      // Surface inferred defaults for the two known keys
      if (key === "tag_policy") console.log(`${key} = ${getTagPolicy(store)} (default)`);
      else if (key === "tag_require_reason") console.log(`${key} = ${getTagRequireReason(store)} (default)`);
      else console.log(`${key} = (unset)`);
    } else {
      console.log(`${key} = ${v}`);
    }
    return;
  }
  if (sub === "set") {
    const key = args[1];
    const value = args[2];
    if (!key || value === undefined) {
      console.error(`stele config set <key> <value>`);
      process.exit(1);
    }
    if (key === "tag_policy" && !["auto", "propose", "locked"].includes(value)) {
      console.error(`tag_policy must be one of: auto, propose, locked`);
      process.exit(1);
    }
    if (key === "tag_require_reason" && !["true", "false"].includes(value)) {
      console.error(`tag_require_reason must be 'true' or 'false'`);
      process.exit(1);
    }
    store.setConfig(key, value);
    console.log(`${key} = ${value}`);
    return;
  }
  console.error(`unknown config subcommand: ${sub} — try list / get / set`);
  process.exit(1);
}

async function main() {
  const [cmd, ...args] = process.argv.slice(2);

  // Storeless commands first — they manipulate config files or registry,
  // never touch a per-project DB.
  if (cmd === "init") return initCommand(args);
  if (cmd === "hooks") return hooksCommand(args);
  if (cmd === "daemon") return daemonCommand(args);
  if (cmd === "projects") return projectsCommand(args);
  if (cmd === "serve") return serveCommand(args);

  let store: Store;
  try {
    store = new Store(resolveDbPath());
  } catch (e) {
    if (e instanceof SteleNotInitializedError) {
      console.error(e.message);
      process.exit(1);
    }
    throw e;
  }

  // milestones / tags / config are per-project (need the store) but have
  // nested subcommands so they don't fit the flat switch pattern.
  if (cmd === "milestones") return milestonesCommand(store, args);
  if (cmd === "tags") return tagsCommand(store, args);
  if (cmd === "config") return configCommand(store, args);

  switch (cmd) {
    // ----- seed from an existing feature-report HTML --------------------------
    case "seed": {
      const { decisions, edges } = parseReport(args[0]);
      for (const d of decisions) store.putDecision(d);
      for (const e of edges) store.addEdge(e);
      console.log(`seeded ${decisions.length} decisions, ${edges.length} edges from ${args[0]}`);
      break;
    }

    // ----- the /decision sink: agent drafts a CapturePayload, pipes it here ---
    // Captures the node, then PROPOSES consolidation edges for the human to confirm.
    case "add": {
      const payload = JSON.parse(readStdin()) as CapturePayload;
      const candidates = proposeEdges(store, payload.decision);
      store.putDecision(payload.decision);
      for (const e of payload.edges || []) store.addEdge(e);

      console.log(`captured ${payload.decision.id} — ${payload.decision.title}`);
      if (payload.edges?.length) console.log(`applied ${payload.edges.length} authored edge(s)`);
      if (payload.tags?.length) {
        const tr = applyCaptureTags(store, payload.tags, payload.decision.id);
        if (tr.applied.length) console.log(`tags applied: ${tr.applied.map((a) => a.name).join(", ")}`);
        if (tr.pending.length) console.log(`tags pending: ${tr.pending.map((p) => `${p.name}(${p.proposalId})`).join(", ")}`);
        if (tr.blocked.length) console.log(`tags blocked: ${tr.blocked.map((b) => b.name).join(", ")}`);
        for (const e of tr.errors) console.log(`tag error "${e.name}": ${e.message}`);
      }
      if (candidates.length) {
        console.log(`\nconsolidate proposes ${candidates.length} edge(s) — confirm with \`resolve\`/\`relate\`:`);
        for (const c of candidates.slice(0, 6))
          console.log(`  · [${(c.confidence * 100) | 0}%] ${c.reason}`);
      }
      break;
    }

    // ----- the cross-session stitch: a later decision closes an old loop ------
    case "resolve": {
      store.addEdge({ from: args[0], to: args[1], kind: "resolves", note: args[2] || "manual" });
      console.log(`${args[1]} now RESOLVED by ${args[0]}`);
      break;
    }
    case "relate": {
      store.addEdge({ from: args[0], to: args[1], kind: "relates", note: args[2] || "manual" });
      console.log(`linked ${args[0]} —relates→ ${args[1]}`);
      break;
    }

    // ----- projection 1: what's waiting for me --------------------------------
    case "resume": {
      const items = resumeDigest(store);
      const htmlFlag = args.indexOf("--html");
      if (htmlFlag >= 0) {
        const out = args[htmlFlag + 1] || join(process.cwd(), "resume.html");
        writeFileSync(out, renderResume(items));
        console.log(`wrote ${out} (${items.length} open loops)`);
      } else {
        console.log(`\n什么在等我 — ${items.length} 个未闭合回路\n`);
        for (const i of items) {
          const tag = i.needsCheck ? " ⚠ CHECK" : "";
          console.log(`  ${i.id}  [${i.bucket}] ${i.ageDays}d${tag}  ${i.title}`);
          if (i.trigger) console.log(`        复审: ${i.trigger}`);
        }
      }
      break;
    }

    // ----- projection 2: how did this come to be ------------------------------
    case "trace": {
      const t = await trace(store, args[0], stubResolver);
      if (!t) { console.log(`no such decision: ${args[0]}`); break; }
      console.log(`\n${t.decision.id} — ${t.decision.title}`);
      console.log(`  status:  ${t.statusLine}`);
      if (t.decision.constraint) console.log(`  约束:    ${t.decision.constraint}`);
      console.log(`  affects: ${t.affects.map((a) => a.label).join(", ")}`);
      if (t.edges.length) {
        console.log(`  graph:`);
        for (const e of t.edges) {
          const arrow = e.direction === "out" ? `—${e.kind}→` : `←${e.kind}—`;
          console.log(`    ${arrow} ${e.otherId} (${e.otherTitle})`);
        }
      }
      break;
    }

    // ----- projection 2b: everything touching an entity -----------------------
    case "trace-entity": {
      const ref: EntityRef = { kind: args[0], id: args[1] };
      const traces = await traceEntity(store, ref, stubResolver);
      console.log(`\n${ref.kind}:${ref.id} — ${traces.length} 个相关决策\n`);
      for (const t of traces) console.log(`  ${t.decision.id}  ${t.statusLine}\n        ${t.decision.title}`);
      break;
    }

    case "list": {
      for (const d of store.allDecisions())
        console.log(`  ${d.id.padEnd(7)} ${d.status.kind.padEnd(11)} ${d.title}`);
      break;
    }

    default:
      console.log(`usage: stele <cmd>
  init                          create .stele/ + .mcp.json + register + hooks + daemon
  hooks <install|uninstall|status>     manage Stop hook + stele-capture skill
  daemon <install|uninstall|status>    multi-tenant always-on serve (launchd / systemd)
  projects <list|remove <slug>>        view/manage the global project registry
  milestones <list|open|close|show>    0.0.6+ — group decisions by milestone / session
  tags <list|propose|apply|confirm|reject|recolor|rename|archive|restore|proposals>
                                       0.0.7+ — tag milestones / decisions
  config <list|get|set>                0.0.7+ — local preferences (e.g. tag_policy)
  serve [--multi] [--port N] [--open]  browser UI (default http://127.0.0.1:3939)
  resume [--html out.html]      "什么在等我" — open loops, needs-check first
  trace <id>                    "怎么发生的" — node + its graph neighbourhood
  trace-entity <kind> <id>      everything touching an entity (file/feature/skill...)
  list                          all decisions by status
  seed <report.html>            ingest a feature-report HTML as decision nodes
  add  < payload.json           capture a decision via stdin (CapturePayload JSON)
  resolve <byId> <defId> [note] mark a deferred/open node resolved by a later decision
  relate  <a> <b> [note]        link two decisions

Store: per-project at .stele/decisions.db. \`stele init\` writes that and
registers the project in ~/.stele/registry.json so the daemon can route to it
at http://127.0.0.1:3939/<slug>/. CLI commands walk up from cwd to find the
.stele/ marker; override with STELE_DB=/abs/path/decisions.db.`);
  }
}

main();
