#!/usr/bin/env -S node --no-warnings
import { writeFileSync, readFileSync, existsSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { Store } from "./store.ts";
import { parseReport } from "./seed.ts";
import { proposeEdges } from "./consolidate.ts";
import { resumeDigest, trace, traceEntity } from "./projections.ts";
import { renderResume } from "./render.ts";
import { stubResolver } from "./resolver.ts";
import { resolveDbPath, SteleNotInitializedError } from "./paths.ts";
import { startServer } from "./serve.ts";
import { installHooks, uninstallHooks, hooksStatus } from "./hooks.ts";
import { installDaemon, uninstallDaemon, daemonStatus } from "./daemon.ts";
import {
  allProjects,
  register as registerProject,
  unregister as unregisterProject,
} from "./registry.ts";
import type { CapturePayload, EntityRef } from "./types.ts";

function readStdin(): string {
  try { return readFileSync(0, "utf8"); } catch { return ""; }
}

// -----------------------------------------------------------------------------
// stele init — bootstrap a project: .stele/ + .stele/README.md + .gitignore
// entry + .mcp.json with the stele server registered.
// -----------------------------------------------------------------------------

const STELE_README = `# .stele/ — decision store for this project

This directory was created by \`stele init\`. It holds **decisions.db**, a
SQLite store of decision provenance for this project: every decision made
about the codebase — what was chosen, what was deferred, what's still
open — lives here as a node in a graph.

## Daily use

Open Claude Code in this project. When a decision crystallizes in the
conversation, type \`/decision\` — the agent drafts the full record and
asks you to confirm.

To see what's waiting on you, ask: *"what's waiting on me?"* The agent
calls \`decision_resume\` and surfaces every open + un-resolved deferred
node, with the most-likely-due ones first.

## Cross-project view

If you organize multiple projects under one parent directory, run
\`stele init\` in the parent too. Decisions captured from any
subdirectory roll up into the parent's \`.stele/\`, giving you a global
view across all the projects under it.

## Backup

\`decisions.db\` is a regular SQLite file. Copy it while no MCP server
is connected. For a hot backup:

    sqlite3 decisions.db ".backup target.db"

## Sharing with a team

By default \`stele init\` adds \`.stele/\` to your project's \`.gitignore\`.
To share decisions with collaborators via git, remove that entry — the
DB file is small and version-friendly for small teams.

---

*Auto-generated by \`stele init\`. Safe to edit or delete. The tool
itself was installed via \`npm install -g stele-mcp\`.*
`;

async function initCommand(args: string[]): Promise<void> {
  let skipDaemon = false;
  let skipHooks = false;
  let port = 3939;
  for (let i = 0; i < args.length; i++) {
    const a = args[i];
    if (a === "--skip-daemon") skipDaemon = true;
    else if (a === "--skip-hooks") skipHooks = true;
    else if (a === "--port") {
      const n = Number(args[++i]);
      if (!Number.isInteger(n) || n < 1 || n > 65535) {
        console.error(`invalid --port value: ${args[i]}`);
        process.exit(1);
      }
      port = n;
    } else {
      console.error(`unknown init flag: ${a}`);
      process.exit(1);
    }
  }

  const cwd = process.cwd();
  const steleDir = join(cwd, ".stele");

  if (existsSync(steleDir)) {
    console.error(`stele already initialized at ${steleDir}`);
    console.error(`(rm -rf .stele to reset — you'll lose all decisions)`);
    process.exit(1);
  }

  mkdirSync(steleDir, { recursive: true });
  writeFileSync(join(steleDir, "README.md"), STELE_README);

  const gitignorePath = join(cwd, ".gitignore");
  let gitignoreNote = "";
  if (existsSync(gitignorePath)) {
    const current = readFileSync(gitignorePath, "utf8");
    if (!/^\.stele\/?$/m.test(current)) {
      const sep = current.endsWith("\n") || current.length === 0 ? "" : "\n";
      writeFileSync(gitignorePath, current + sep + ".stele/\n");
      gitignoreNote = "added .stele/ to .gitignore";
    } else {
      gitignoreNote = ".gitignore already mentions .stele/";
    }
  } else {
    writeFileSync(gitignorePath, ".stele/\n");
    gitignoreNote = "wrote .gitignore with .stele/";
  }

  const mcpPath = join(cwd, ".mcp.json");
  let mcpConfig: { mcpServers?: Record<string, unknown> } = { mcpServers: {} };
  let mcpNote = "wrote .mcp.json with stele entry";
  if (existsSync(mcpPath)) {
    let parsed: unknown;
    try {
      parsed = JSON.parse(readFileSync(mcpPath, "utf8"));
    } catch {
      console.error(`existing .mcp.json is not valid JSON — refusing to overwrite`);
      process.exit(1);
    }
    if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
      console.error(`existing .mcp.json is not an object — refusing to overwrite`);
      process.exit(1);
    }
    mcpConfig = parsed as typeof mcpConfig;
    if (!mcpConfig.mcpServers || typeof mcpConfig.mcpServers !== "object") {
      mcpConfig.mcpServers = {};
    }
    mcpNote = mcpConfig.mcpServers!.stele
      ? "updated stele entry in existing .mcp.json"
      : "merged stele entry into existing .mcp.json";
  }
  mcpConfig.mcpServers!.stele = { command: "stele-mcp" };
  writeFileSync(mcpPath, JSON.stringify(mcpConfig, null, 2) + "\n");

  console.log(`stele initialized at ${steleDir}`);
  console.log(``);
  console.log(`  wrote .stele/README.md`);
  console.log(`  ${mcpNote}`);
  console.log(`  ${gitignoreNote}`);

  // Register this project in the global registry so the multi-tenant daemon
  // can route /<slug>/ to it.
  let projectSlug: string;
  try {
    const reg = registerProject(cwd);
    projectSlug = reg.slug;
    console.log(`  ${reg.isNew ? "registered" : "already registered"} as slug "${reg.slug}"`);
  } catch (e) {
    projectSlug = "<this-project>";
    console.error(`  ⚠ registry write failed (continuing): ${(e as Error).message}`);
  }

  // Default-install hooks (Stop hook + stele-capture skill) — opt-out with --skip-hooks
  if (!skipHooks) {
    try {
      const r = installHooks(cwd);
      console.log(`  ${r.hook}`);
      console.log(`  ${r.skill}`);
      console.log(`  ${r.command}`);
      console.log(`  ${r.settings}`);
    } catch (e) {
      console.error(`  ⚠ hooks install failed (continuing): ${(e as Error).message}`);
    }
  }

  // Default-install daemon (launchd / systemd) — opt-out with --skip-daemon.
  // Install is idempotent: if already installed, nothing happens but legacy
  // per-project plists/units (from pre-0.0.3) get swept and their projects
  // get registered into the global registry.
  if (!skipDaemon) {
    if (process.platform !== "darwin" && process.platform !== "linux") {
      console.log(`  ⓘ daemon not installed (unsupported platform: ${process.platform})`);
    } else {
      try {
        const r = await installDaemon({ port });
        console.log(`  installed ${r.platform} daemon — http://127.0.0.1:${r.port} (loaded: ${r.loaded ? "yes" : "no"})`);
        for (const n of r.notes) console.log(`    · ${n}`);
      } catch (e) {
        console.error(`  ⚠ daemon install failed (continuing): ${(e as Error).message}`);
        console.error(`    you can retry with: stele daemon install --port <N>`);
      }
    }
  }

  console.log(``);
  console.log(`Next:`);
  console.log(`  1. Restart Claude Code in this directory (it picks up .mcp.json).`);
  if (skipDaemon) {
    console.log(`  2. Run \`stele serve --multi\` to launch the browser UI.`);
  } else {
    console.log(`  2. Open http://127.0.0.1:${port}/${projectSlug}/ — daemon serves it always-on.`);
  }
  console.log(`  3. Ask "what's waiting on me?" to see open loops.`);
}

// -----------------------------------------------------------------------------

function hooksCommand(args: string[]): void {
  const sub = args[0];
  const cwd = process.cwd();
  if (sub === "install") {
    try {
      const r = installHooks(cwd);
      console.log(`hooks installed in ${cwd}:`);
      console.log(`  ${r.hook}`);
      console.log(`  ${r.skill}`);
      console.log(`  ${r.command}`);
      console.log(`  ${r.settings}`);
    } catch (e) {
      console.error(`hooks install failed: ${(e as Error).message}`);
      process.exit(1);
    }
  } else if (sub === "uninstall") {
    try {
      const r = uninstallHooks(cwd);
      console.log(`hooks uninstalled from ${cwd}:`);
      console.log(`  ${r.hook}`);
      console.log(`  ${r.skill}`);
      console.log(`  ${r.command}`);
      console.log(`  ${r.settings}`);
    } catch (e) {
      console.error(`hooks uninstall failed: ${(e as Error).message}`);
      process.exit(1);
    }
  } else if (sub === "status" || sub === undefined) {
    const s = hooksStatus(cwd);
    const mark = (b: boolean) => (b ? "✓" : "✗");
    console.log(`stele hooks status (${cwd}):`);
    console.log(`  ${mark(s.hook)}  .claude/hooks/stele-stop.sh`);
    console.log(`  ${mark(s.skill)}  .claude/skills/stele-capture/SKILL.md`);
    console.log(`  ${mark(s.command)}  .claude/commands/decision.md`);
    console.log(`  ${mark(s.settingsHasEntry)}  Stop hook in .claude/settings.json`);
  } else {
    console.error(`unknown hooks subcommand: ${sub} — try install / uninstall / status`);
    process.exit(1);
  }
}

async function daemonCommand(args: string[]): Promise<void> {
  const sub = args[0];

  // Parse flags from args[1..]
  let port = 3939;
  let printUnit = false;
  for (let i = 1; i < args.length; i++) {
    const a = args[i];
    if (a === "--port") {
      const n = Number(args[++i]);
      if (!Number.isInteger(n) || n < 1 || n > 65535) {
        console.error(`invalid --port value: ${args[i]}`);
        process.exit(1);
      }
      port = n;
    } else if (a === "--print-unit") {
      printUnit = true;
    } else {
      console.error(`unknown daemon flag: ${a}`);
      process.exit(1);
    }
  }

  if (sub === "install") {
    try {
      const r = await installDaemon({ port, printUnit });
      if (printUnit) return; // unit printed to stdout already
      console.log(`stele daemon installed (${r.platform}, multi-tenant):`);
      console.log(`  unit:       ${r.unitPath}`);
      console.log(`  invocation: ${r.invocation}`);
      console.log(`  port:       ${r.port}`);
      console.log(`  loaded:     ${r.loaded ? "yes" : "no"}`);
      for (const n of r.notes) console.log(`  · ${n}`);
      if (r.legacy.registered.length > 0) {
        console.log(`  · imported projects from legacy daemons:`);
        for (const p of r.legacy.registered) console.log(`      ${p}`);
      }
      if (r.loaded) console.log(`\n  → http://127.0.0.1:${r.port}/`);
    } catch (e) {
      console.error(`daemon install failed: ${(e as Error).message}`);
      process.exit(1);
    }
  } else if (sub === "uninstall") {
    const r = uninstallDaemon();
    console.log(`stele daemon uninstalled:`);
    for (const n of r.notes) console.log(`  · ${n}`);
  } else if (sub === "status" || sub === undefined) {
    const s = daemonStatus();
    const n = allProjects().length;
    console.log(`stele daemon status:`);
    console.log(`  platform:           ${s.platform}`);
    console.log(`  unit file:          ${s.unitPresent ? "✓" : "✗"} ${s.unitPath}`);
    console.log(`  loaded:             ${s.loaded ? "✓" : "✗"} (${s.loadedNote})`);
    console.log(`  registered projects: ${n}`);
  } else {
    console.error(`unknown daemon subcommand: ${sub} — try install / uninstall / status`);
    process.exit(1);
  }
}

function projectsCommand(args: string[]): void {
  const sub = args[0];
  if (sub === undefined || sub === "list") {
    const projects = allProjects();
    if (projects.length === 0) {
      console.log(`no projects registered. Run \`stele init\` in a project root.`);
      return;
    }
    console.log(`${projects.length} registered project(s):`);
    const w = Math.max(...projects.map((p) => p.slug.length));
    for (const p of projects) {
      console.log(`  ${p.slug.padEnd(w)}  ${p.path}`);
    }
  } else if (sub === "remove") {
    const target = args[1];
    if (!target) {
      console.error(`stele projects remove <slug-or-path>`);
      process.exit(1);
    }
    const removed = unregisterProject(target);
    if (removed) console.log(`removed ${target} from registry`);
    else {
      console.error(`no project matched "${target}"`);
      process.exit(1);
    }
  } else {
    console.error(`unknown projects subcommand: ${sub} — try list / remove`);
    process.exit(1);
  }
}

async function serveCommand(args: string[]): Promise<void> {
  let port = 3939;
  let host = "127.0.0.1";
  let open = false;
  let multi = false;
  for (let i = 0; i < args.length; i++) {
    const a = args[i];
    if (a === "--port") {
      const n = Number(args[++i]);
      if (!Number.isInteger(n) || n < 1 || n > 65535) {
        console.error(`invalid --port value: ${args[i]}`);
        process.exit(1);
      }
      port = n;
    } else if (a === "--host") {
      host = args[++i];
      if (!host) {
        console.error(`--host requires a value`);
        process.exit(1);
      }
    } else if (a === "--open") {
      open = true;
    } else if (a === "--multi") {
      multi = true;
    } else {
      console.error(`unknown serve flag: ${a}`);
      process.exit(1);
    }
  }
  if (multi) {
    await startServer({ multi: true, port, host, open });
    return;
  }
  // Single-project mode: resolve a store from cwd
  let store: Store;
  try {
    store = new Store(resolveDbPath());
  } catch (e) {
    if (e instanceof SteleNotInitializedError) {
      console.error(e.message);
      process.exit(1);
    }
    throw e;
  }
  await startServer({ store, port, host, open });
}

async function main() {
  const [cmd, ...args] = process.argv.slice(2);

  // Storeless commands first — they manipulate config files or registry,
  // never touch a per-project DB.
  if (cmd === "init") return initCommand(args);
  if (cmd === "hooks") return hooksCommand(args);
  if (cmd === "daemon") return daemonCommand(args);
  if (cmd === "projects") return projectsCommand(args);
  if (cmd === "serve") return serveCommand(args);

  let store: Store;
  try {
    store = new Store(resolveDbPath());
  } catch (e) {
    if (e instanceof SteleNotInitializedError) {
      console.error(e.message);
      process.exit(1);
    }
    throw e;
  }

  switch (cmd) {
    // ----- seed from an existing feature-report HTML --------------------------
    case "seed": {
      const { decisions, edges } = parseReport(args[0]);
      for (const d of decisions) store.putDecision(d);
      for (const e of edges) store.addEdge(e);
      console.log(`seeded ${decisions.length} decisions, ${edges.length} edges from ${args[0]}`);
      break;
    }

    // ----- the /decision sink: agent drafts a CapturePayload, pipes it here ---
    // Captures the node, then PROPOSES consolidation edges for the human to confirm.
    case "add": {
      const payload = JSON.parse(readStdin()) as CapturePayload;
      const candidates = proposeEdges(store, payload.decision);
      store.putDecision(payload.decision);
      for (const e of payload.edges || []) store.addEdge(e);

      console.log(`captured ${payload.decision.id} — ${payload.decision.title}`);
      if (payload.edges?.length) console.log(`applied ${payload.edges.length} authored edge(s)`);
      if (candidates.length) {
        console.log(`\nconsolidate proposes ${candidates.length} edge(s) — confirm with \`resolve\`/\`relate\`:`);
        for (const c of candidates.slice(0, 6))
          console.log(`  · [${(c.confidence * 100) | 0}%] ${c.reason}`);
      }
      break;
    }

    // ----- the cross-session stitch: a later decision closes an old loop ------
    case "resolve": {
      store.addEdge({ from: args[0], to: args[1], kind: "resolves", note: args[2] || "manual" });
      console.log(`${args[1]} now RESOLVED by ${args[0]}`);
      break;
    }
    case "relate": {
      store.addEdge({ from: args[0], to: args[1], kind: "relates", note: args[2] || "manual" });
      console.log(`linked ${args[0]} —relates→ ${args[1]}`);
      break;
    }

    // ----- projection 1: what's waiting for me --------------------------------
    case "resume": {
      const items = resumeDigest(store);
      const htmlFlag = args.indexOf("--html");
      if (htmlFlag >= 0) {
        const out = args[htmlFlag + 1] || join(process.cwd(), "resume.html");
        writeFileSync(out, renderResume(items));
        console.log(`wrote ${out} (${items.length} open loops)`);
      } else {
        console.log(`\n什么在等我 — ${items.length} 个未闭合回路\n`);
        for (const i of items) {
          const tag = i.needsCheck ? " ⚠ CHECK" : "";
          console.log(`  ${i.id}  [${i.bucket}] ${i.ageDays}d${tag}  ${i.title}`);
          if (i.trigger) console.log(`        复审: ${i.trigger}`);
        }
      }
      break;
    }

    // ----- projection 2: how did this come to be ------------------------------
    case "trace": {
      const t = await trace(store, args[0], stubResolver);
      if (!t) { console.log(`no such decision: ${args[0]}`); break; }
      console.log(`\n${t.decision.id} — ${t.decision.title}`);
      console.log(`  status:  ${t.statusLine}`);
      if (t.decision.constraint) console.log(`  约束:    ${t.decision.constraint}`);
      console.log(`  affects: ${t.affects.map((a) => a.label).join(", ")}`);
      if (t.edges.length) {
        console.log(`  graph:`);
        for (const e of t.edges) {
          const arrow = e.direction === "out" ? `—${e.kind}→` : `←${e.kind}—`;
          console.log(`    ${arrow} ${e.otherId} (${e.otherTitle})`);
        }
      }
      break;
    }

    // ----- projection 2b: everything touching an entity -----------------------
    case "trace-entity": {
      const ref: EntityRef = { kind: args[0], id: args[1] };
      const traces = await traceEntity(store, ref, stubResolver);
      console.log(`\n${ref.kind}:${ref.id} — ${traces.length} 个相关决策\n`);
      for (const t of traces) console.log(`  ${t.decision.id}  ${t.statusLine}\n        ${t.decision.title}`);
      break;
    }

    case "list": {
      for (const d of store.allDecisions())
        console.log(`  ${d.id.padEnd(7)} ${d.status.kind.padEnd(11)} ${d.title}`);
      break;
    }

    default:
      console.log(`usage: stele <cmd>
  init                          create .stele/ + .mcp.json + register + hooks + daemon
  hooks <install|uninstall|status>     manage Stop hook + stele-capture skill
  daemon <install|uninstall|status>    multi-tenant always-on serve (launchd / systemd)
  projects <list|remove <slug>>        view/manage the global project registry
  serve [--multi] [--port N] [--open]  browser UI (default http://127.0.0.1:3939)
  resume [--html out.html]      "什么在等我" — open loops, needs-check first
  trace <id>                    "怎么发生的" — node + its graph neighbourhood
  trace-entity <kind> <id>      everything touching an entity (file/feature/skill...)
  list                          all decisions by status
  seed <report.html>            ingest a feature-report HTML as decision nodes
  add  < payload.json           capture a decision via stdin (CapturePayload JSON)
  resolve <byId> <defId> [note] mark a deferred/open node resolved by a later decision
  relate  <a> <b> [note]        link two decisions

Store: per-project at .stele/decisions.db. \`stele init\` writes that and
registers the project in ~/.stele/registry.json so the daemon can route to it
at http://127.0.0.1:3939/<slug>/. CLI commands walk up from cwd to find the
.stele/ marker; override with STELE_DB=/abs/path/decisions.db.`);
  }
}

main();
